export const GRAPH_DATA_REQUEST = 'GRAPH_DATA_REQUEST';
export const GRAPH_DATA_SUCCESS = 'GRAPH_DATA_SUCCESS';
export const GRAPH_DATA_ERROR = 'GRAPH_DATA_ERROR';
export const GET_GRAPH_DATA = 'GET_GRAPH_DATA';
